name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-type-check:
    name: Lint, Type Check, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_MARKETPLACE_API_URL: https://api-dev.solscale.co/graphql
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: 670549849584-po46qh9j1b6khdlpccr83djp8a35s07g.apps.googleusercontent.com
          NEXT_PUBLIC_LINE_CHANNEL_ID: "2010730980"
